routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
//======================================//
//========= Social Login Routes ========//
//======================================//
Route::get('auth/{social}', 'SocialLoginController@redirectToProvider')->name('social_login');
Route::get('auth/{social}/callback', 'SocialLoginController@handleProviderCallback');


Route::get('artisan', function() {
    Artisan::call('route:list');
    dd(Artisan::output());
});
Route::group(['prefix' => 'admin'], function() {
    Voyager::routes();

    //======================================//
    //==== Exam Question & Answers Routes ===//
    //======================================//
    Route::prefix('exam_questions')->name('admin.exam_questions.')->middleware('admin.user')->group(function() {
        Route::get('{exam}/show', 'ExamQuestionsController@show')->name('show');
        Route::delete('{question}/delete', 'ExamQuestionsController@destroy')->name('delete');
        Route::get('{question}/edit', 'ExamQuestionsController@edit')->name('edit');
        Route::put('{question}', 'ExamQuestionsController@update')->name('update');
        Route::delete('{answer}', 'ExamQuestionsController@destroy_answer')->name('delete_answer');
        Route::post('store', 'ExamQuestionsController@store')->name('store');
        Route::get('{exam}/create', 'ExamQuestionsController@create')->name('create');
        Route::post('remove', 'ExamQuestionsController@remove')->name('remove_img');
    });


    //======================================//
    //======= Exam Sections Routes =========//
    //======================================//
    Route::prefix('exam_sections')->name('admin.exam_sections.')->middleware('admin.user')->group(function() {
        Route::get('{exam}/show', 'ExamSectionsController@show')->name('show');
        Route::get('{section}/edit', 'ExamSectionsController@edit')->name('edit');
        Route::get('{exam}/create', 'ExamSectionsController@create')->name('create');
        Route::post('{exam}', 'ExamSectionsController@store')->name('store');
        Route::put('{section}', 'ExamSectionsController@update')->name('update');
        Route::delete('{section}', 'ExamSectionsController@destroy')->name('delete');
    });
});

Route::get('/', 'HomeController@index')->name('home');
Route::get('about-us', 'HomeController@about')->name('about');
Route::get('contact', 'HomeController@show_contact')->name('contact');
Route::post('contact', 'HomeController@contact');
Route::get('pages/{page}', 'HomeController@pages')->name('pages');

//======================================//
//========= Qeyas News Routes ==========//
//======================================//
Route::prefix('news')->name('news.')->group(function() {
    Route::get('/', 'NewsController@index')->name('index');
    Route::get('{news}/show', 'NewsController@show')->name('show');
});


//======================================//
//========= Categories Routes ==========//
//======================================//
Route::prefix('categories')->name('categories.')->group(function() {
    Route::get('/', 'CategoriesController@index')->name('index');
    Route::get('{category}/show', 'CategoriesController@show')->name('show');
});

//======================================//
//============ Exam Routes =============//
//======================================//
Route::prefix('exams')->name('exams.')->group(function() {
    Route::get('/', 'ExamsController@index')->name('index');
    Route::get('{exam}/toplist', 'ExamsController@toplist')->name('toplist');
    Route::get('search', 'ExamsController@search')->name('search');
    Route::middleware('auth')->group(function(){
        Route::get('{exam}/show', 'ExamsController@show')->name('show');
        Route::get('{exam}/start', 'ExamsController@start')->name('start');
        Route::get('{exam}/buy', 'ExamsController@buy')->name('buy');
        Route::post('finish', 'ExamsController@post_exam')->name('post_exam');
        Route::get('{report}/report', 'ExamsController@report')->name('report');
        Route::get('/paypal/checkout', 'PayPalController@checkout_exam')
            ->name('checkout');
        Route::get('/paypal/checkout/success', 'PayPalController@checkout_exam_success')
            ->name('checkout_success');
    });

});

//======================================//
//============ User Routes =============//
//======================================//
Route::prefix('user')->name('user.')->middleware('auth')->group(function() {
    Route::get('profile', 'UserController@profile')->name('profile');
    Route::get('profile/edit', 'UserController@edit')->name('edit-profile');
    Route::post('profile', 'UserController@update')->name('update-profile');
    Route::post('update_password', 'UserController@update_password')->name('update_password');
    Route::get('notifications', 'UserController@notifications')->name('notifications');
});

//======================================//
//=========== Courses Routes ===========//
//======================================//
Route::prefix('courses')->name('courses.')->group(function() {
    Route::get('/', 'CoursesController@index')->name('index');
    Route::get('/{course}/show', 'CoursesController@show')->name('show');
    Route::get('search', 'CoursesController@search')->name('search');
    Route::post('{course}/request', 'CoursesController@request')
        ->middleware('auth')
        ->name('request');
});

//======================================//
//=========== Books Routes ===========//
//======================================//
Route::prefix('books')->name('books.')->group(function() {
    Route::get('/', 'BooksController@index')->name('index');
    Route::get('{book}/show', 'BooksController@show')->name('show');
    Route::middleware('auth')->group(function() {
        Route::get('{book}/view', 'BooksController@view')->name('view');
        Route::get('{book}/download', 'BooksController@download')->name('download');
        Route::get('{book}/buy', 'BooksController@buy')->name('buy');
        Route::get('paypal/checkout', 'PayPalController@checkout_book')
            ->name('checkout');
        Route::get('paypal/checkout/success', 'PayPalController@checkout_book_success')
            ->name('checkout_success');
    });
});

//======================================//
//=========== Videos Routes ===========//
//======================================//
Route::prefix('videos')->name('videos.')->group(function() {
    Route::get('/', 'VideosController@index')->name('index');
    Route::get('{video}/show', 'VideosController@show')->name('show');
});

app/Book.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

/**
 * App\Book
 *
 * @property int $id
 * @property string $book_title
 * @property string $book_photo
 * @property string $book_description
 * @property string $book_price
 * @property string $book_release_date
 * @property string $book_url
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Book newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Book newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Book query()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Book whereBookDescription($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Book whereBookPhoto($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Book whereBookPrice($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Book whereBookReleaseDate($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Book whereBookTitle($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Book whereBookUrl($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Book whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Book whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Book whereUpdatedAt($value)
 * @mixin \Eloquent
 */
class Book extends Model
{
    protected $table = 'books';
    private $ar_month = [
        'Jan' => 'يناير',
        'Feb' => 'فبراير',
        'Mar' => 'مارس',
        'Apr' => 'أبريل',
        'May' => 'مايو',
        'Jun' => 'يونيو',
        'Jul' => 'يوليو',
        'Aug' => 'أغسطس',
        'Sep' => 'سبتمبر',
        'Oct' => 'أكتوبر',
        'Nov' => 'نوفمبر',
        'Dec' => 'ديسمبر',
    ];

    public function getReleaseDateAttribute() {
        $value = Carbon::parse($this->book_release_date);
        return "$value->day " . $this->ar_month[$value->shortEnglishMonth] . " $value->year";
    }

    public function getUrlAttribute() {
        return json_decode($this->book_url)[0]->download_link;
    }

    public function user_payment() {
        return $this->hasOne(Payment::class)->where('user_id', \Auth::id() ?? 0);
    }

    public function getPaymentDateAttribute() {
        $date = $this->user_payment->created_at;
        return "$date->day " . $this->ar_month[$date->shortEnglishMonth] . " $date->year";
    }
}

app/Http/Controllers/BooksController.php
<?php

namespace App\Http\Controllers;

use App\Book;
use Illuminate\Http\Request;
use TCG\Voyager\Facades\Voyager;

class BooksController extends Controller
{

    public function index() {
        $books = Book::paginate(10);
        $title = 'الكتب الالكترونية';
        return view('books.index', compact('books', 'title'));
    }

    public function show(Book $book) {
        $title = $book->book_title;
        return view('books.show', compact('book', 'title'));
    }

    public function view(Book $book) {
        if($book->book_price == 0 || \Auth::user()->has_book($book->id)) {
            return view('books.view', compact('book'));
        }
        return redirect()->route('books.buy', $book);
    }

    public function download(Book $book) {
        $url = storage_path("app/public/{$book->url}");
        if($book->book_price == 0 || \Auth::user()->has_book($book->id)) {
            if(file_exists($url)){
                return response()->download($url, "$book->book_title.pdf", [
                    'Content-Type: application/pdf',
                ]);
            }
            abort(404, 'الكتاب غير موجود');
        }
        return redirect()->route('books.buy', $book);
    }

    public function buy(Book $book) {
        if($book->book_price == 0 || \Auth::user()->has_book($book->id)){
            return redirect()->route('books.show', $book);
        }
        $title = 'شراء كتاب';
        return view('books.buy', compact('book', 'title'));
    }
}

resources/views/books/buy.blade.php
@extends('layouts.app')
@section('content')
    <section class="banner inner-page">
        <div class="banner-img"><img src="{{ asset('images/banner/register-bannerImg.jpg') }}" alt=""></div>
        <div class="page-title">
            <div class="container">
                <h1 class="Tajawal-font">شراء كتاب</h1>
            </div>
        </div>
    </section>
    <section class="breadcrumb">
        <div class="container">
            <ul>
                <li><a href="{{ route('home') }}">الرئيسية</a></li>
                <li><a href="{{ route('books.index') }}">الكتب الإلكترونية</a></li>
                <li>شراء كتاب</li>
            </ul>
        </div>
    </section>
    <section class="courses-view list-view">
        @if(session('fail'))
            <div class="alert alert-danger">
                {{ session('fail') }}
            </div>
        @elseif(session('success'))
            <div class="alert alert-success">
                {{ session('success') }}
            </div>
        @endif
        <div class="container">
            <div class="row">
                <div class="test-price">
                    <h3 class="Tajawal-font fontsize-30">السعر : {{ $book->book_price }} دولار</h3>
                </div>
                <div class="tab">
                    <button class="tablinks active" onclick="openCity(event, 'visa')">
                        <img class="pay-imgs" src="{{ asset('images/visa.png') }}" alt="">
                        <span>باي بال</span>
                    </button>
                    {{--<button class="tablinks" onclick="openCity(event, 'master-card')">--}}
                    {{--<img class="pay-imgs" src="images/{{ asset('master-card.png') }}" alt="">--}}
                    {{--<span>ماستر كارد</span>--}}
                    {{--</button>--}}
                    {{--<button class="tablinks" onclick="openCity(event, 'Tokyo')">--}}
                    {{--<img class="pay-imgs" src="{{ asset('images/sadad.jpg') }}" alt="">--}}
                    {{--<span>سداد</span>--}}
                    {{--</button>--}}
                    {{--<button class="tablinks" onclick="openCity(event, 'Tokyo')">--}}
                    {{--<img class="pay-imgs" src="{{ asset('images/sadad.jpg') }}" alt="">--}}
                    {{--<span>نظام دفع من موبايلي</span>--}}
                    {{--</button>--}}
                </div>
                <div id="visa" class="tabcontent">
                    <form class="payment-form" action="{{ route('books.checkout') }}" method="get">
                        <h3 class="Tajawal-font">دفع باي بال : <img class="pay-imgs" src="{{ asset('images/visa.png') }}" alt=""></h3>
                        <div class="row col-50">
                            <input type="hidden" name="book_id" value="{{ $book->id }}">
                            {{--<div class="form-group col-md-12">--}}
                            {{--<label for="cname">Name on Card</label>--}}
                            {{--<input type="text" id="cname" name="cardname" placeholder="John More Doe">--}}
                            {{--</div>--}}
                            {{--<div class="form-group col-md-12">--}}
                            {{--<label for="ccnum">Credit card number</label>--}}
                            {{--<input type="text" id="ccnum" name="cardnumber" placeholder="1111-2222-3333-4444">--}}
                            {{--</div>--}}
                            {{--<div class="form-group col-md-6">--}}
                            {{--<label for="expmonth">Exp Month</label>--}}
                            {{--<input type="text" id="expmonth" name="expmonth" placeholder="September">--}}
                            {{--</div>--}}
                            {{--<div class="form-group col-md-6">--}}
                            {{--<label for="expyear">Exp Year</label>--}}
                            {{--<input type="text" id="expyear" name="expyear" placeholder="2018">--}}
                            {{--</div>--}}
                            {{--<div class="form-group col-md-12">--}}
                            {{--<label for="cvv">CVV</label>--}}
                            {{--<input type="text" id="cvv" name="cvv" placeholder="352">--}}
                            {{--</div>--}}
                            <div class="text-center">
                                <button type="submit" class="btn">ادفع الآن</button>
                            </div>
                        </div>
                    </form>
                </div>
                {{--<div id="master-card" class="tabcontent">--}}
                {{--<form class="payment-form" action="index.html" method="post">--}}
                {{--<h3 class="Tajawal-font">دفع بالماستر كارد:  <img class="pay-imgs" src="{{ asset('images/master-card.png') }}" alt=""></h3>--}}
                {{--<div class="row col-50">--}}
                {{--<div class="form-group col-md-12">--}}
                {{--<label for="cname">Name on Card</label>--}}
                {{--<input type="text" id="cname" name="cardname" placeholder="John More Doe">--}}
                {{--</div>--}}
                {{--<div class="form-group col-md-12">--}}
                {{--<label for="ccnum">Credit card number</label>--}}
                {{--<input type="text" id="ccnum" name="cardnumber" placeholder="1111-2222-3333-4444">--}}
                {{--</div>--}}
                {{--<div class="form-group col-md-6">--}}
                {{--<label for="expmonth">Exp Month</label>--}}
                {{--<input type="text" id="expmonth" name="expmonth" placeholder="September">--}}
                {{--</div>--}}
                {{--<div class="form-group col-md-6">--}}
                {{--<label for="expyear">Exp Year</label>--}}
                {{--<input type="text" id="expyear" name="expyear" placeholder="2018">--}}
                {{--</div>--}}
                {{--<div class="form-group col-md-12">--}}
                {{--<label for="cvv">CVV</label>--}}
                {{--<input type="text" id="cvv" name="cvv" placeholder="352">--}}
                {{--</div>--}}
                {{--<div class="text-center">--}}
                {{--<a href="quiz-intro.html" class="btn">إدفع الآن</a>--}}
                {{--</div>--}}
                {{--</div>--}}
                {{--</form>--}}
                {{--</div>--}}
                {{--<div id="Tokyo" class="tabcontent">--}}
                {{--<form class="payment-form" action="index.html" method="post">--}}
                {{--<h3 class="Tajawal-font">دفع بسداد  <img class="pay-imgs" src="{{ asset('images/sadad.jpg') }}" alt=""></h3>--}}
                {{--<div class="row col-50">--}}
                {{--<div class="form-group col-md-12">--}}
                {{--<label for="cname">اسم مستخدم حساب سداد</label>--}}
                {{--<input type="text" id="cname" name="cardname" placeholder="أدخل اسم مستخدم حساب سداد هنا">--}}
                {{--</div>--}}
                {{--<div class="text-center">--}}
                {{--<a href="quiz-intro.html" class="btn">إدفع الآن</a>--}}
                {{--</div>--}}
                {{--</div>--}}
                {{--</form>--}}
                {{--</div>--}}
            </div>
        </div>
    </section>
@endsection

resources/views/books/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="banner inner-page">
        <div class="banner-img"><img src="{{ asset('images/banner/register-bannerImg.jpg') }}" alt=""></div>
        <div class="page-title">
            <div class="container">
                <h1 class="Tajawal-font">الكتب الإلكترونية</h1>
            </div>
        </div>
    </section>
    <section class="breadcrumb">
        <div class="container">
            <ul>
                <li><a href="{{ route('home') }}">الرئيسية</a></li>
                <li><a href="{{ route('books.index') }}">الكتب الإلكترونية</a></li>
            </ul>
        </div>
    </section>
    <div class="user-dashboard">
        <div class="container">
            <div class="archived-course">
                @foreach($books as $book)
                    <div class="course-list">
                        <div class="img">
                            <img src="{{ Voyager::image($book->book_photo) }}" alt="">
                        </div>
                        <div class="info">
                            <div class="name Tajawal-font">
                                <a href="{{ route('books.show', $book) }}">{{ $book->book_title }}</a>
                            </div>
                            <div class="date">{{ $book->release_date }}</div>
                            <p>{{ str_limit($book->book_description, 200) }}</p>
                            <div class="btn-block">
                                @auth('web')
                                    {{--@if($book->book_price == 0 || Auth::user()->has_book($book->id))--}}
                                        <a href="{{ route('books.view', $book) }}" class="btn">تصفح الكتاب</a>
                                        <a href="{{ route('books.download', $book) }}" class="btn3"><i class="fa fa-download" aria-hidden="true"></i> تحميل الكتاب</a>
                                    {{--@endif--}}
                                @endauth
                            </div>
                        </div>
                    </div>
                @endforeach
                {{ $books->links() }}
            </div>
        </div>
    </div>
@endsection

resources/views/books/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="banner inner-page">
        <div class="banner-img"><img src="{{ asset('images/banner/register-bannerImg.jpg') }}" alt=""></div>
        <div class="page-title">
            <div class="container">
                <h1 class="Tajawal-font">تفاصيل الكتاب</h1>
            </div>
        </div>
    </section>
    <section class="breadcrumb">
        <div class="container">
            <ul>
                <li><a href="{{ route('home') }}">الرئيسية</a></li>
                <li><a href="{{ route('books.index') }}">الكتب الإلكترونية</a></li>
                <li>{{ $book->book_title }}</li>
            </ul>
        </div>
    </section>
    <div class="blog-page blog-details">
        @if(session('fail'))
            <div class="alert alert-danger">
                {{ session('fail') }}
            </div>
        @elseif(session('success'))
            <div class="alert alert-success">
                {{ session('success') }}
            </div>
        @endif
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <div class="blog-slide">
                        <div class="img" style="min-height: 100px;">
                            <img src="{{ Voyager::image($book->book_photo, asset('images/blog/img1.jpg')) }}" alt="">
                            <div class="date">
                                <span class="fontsize-30">{{ $book->book_price }} $</span>
                            </div>
                        </div>
                        <div class="info">
                            <div class="name">
                                {{ $book->book_title }}
                            </div>
                            <div class="post-info">
                                <span><i class="fa fa-calendar"></i>{{ $book->release_date }}</span>
                            </div>
                            <p>{{ $book->book_description }}</p>
                            <div class="btn-block">
                                @if($book->book_price == 0 || (Auth::check() && Auth::user()->has_book($book->id)))
                                    <a href="{{ route('books.view', $book) }}" class="btn">تصفح الكتاب</a>
                                    <a href="{{ route('books.download', $book) }}" class="btn3"><i class="fa fa-download" aria-hidden="true"></i> تحميل الكتاب</a>
                                @else
                                    <a href="{{ route('books.buy', $book) }}" class="btn">اشترِ الكتاب</a>
                                @endif
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/books/view.blade.php
<!DOCTYPE html>
<html lang="en" dir="rtl">
<head>
    <!-- Meta information -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"><!-- Mobile Specific Metas -->

    <!-- Title -->
    <title>{{ $book->book_title }}</title>

    <!-- favicon icon -->
    <link rel="shortcut icon" href="{{ asset('images/Favicon.ico') }}">

    <!-- CSS Stylesheet -->
    <link href="{{ asset('css/bootstrap.css') }}" rel="stylesheet"><!-- bootstrap css -->
    <link href="{{ asset('css/bootstrap-rtl.min.css') }}" rel="stylesheet"><!-- bootstrap rtl css -->
    <link href="{{ asset('css/owl.carousel.css') }}" rel="stylesheet"><!-- carousel Slider -->
    <link href="{{ asset('css/font-awesome.css') }}" rel="stylesheet"><!-- font awesome -->
    <link href="{{ asset('css/docs.css') }}" rel="stylesheet"><!--  template structure css -->
    <link href="https://fonts.googleapis.com/css?family=Arima+Madurai:100,200,300,400,500,700,800,900%7CPT+Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Tajawal:500&display=swap" rel="stylesheet">
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->

</head>

<body>
    <div class="container-fluid">
        <embed src="{{ Voyager::image($book->url) }}" type="application/pdf" width="100%" height="700px" />
    </div>
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

    <script type="text/javascript" src="{{ asset('js/jquery-1.12.4.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('js/bootstrap.js') }}"></script>
    <script type="text/javascript" src="{{ asset('js/owl.carousel.js') }}"></script>
    <script type="text/javascript" src="{{ asset('js/jquery.form-validator.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('js/placeholder.js') }}"></script>
    <script type="text/javascript" src="{{ asset('js/coustem.js') }}"></script>
</body>
</html>