routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
//======================================//
//========= Social Login Routes ========//
//======================================//
Route::get('auth/{social}', 'SocialLoginController@redirectToProvider')->name('social_login');
Route::get('auth/{social}/callback', 'SocialLoginController@handleProviderCallback');


Route::get('artisan', function() {
    Artisan::call('route:list');
    dd(Artisan::output());
});
Route::group(['prefix' => 'admin'], function() {
    Voyager::routes();

    //======================================//
    //==== Exam Question & Answers Routes ===//
    //======================================//
    Route::prefix('exam_questions')->name('admin.exam_questions.')->middleware('admin.user')->group(function() {
        Route::get('{exam}/show', 'ExamQuestionsController@show')->name('show');
        Route::delete('{question}/delete', 'ExamQuestionsController@destroy')->name('delete');
        Route::get('{question}/edit', 'ExamQuestionsController@edit')->name('edit');
        Route::put('{question}', 'ExamQuestionsController@update')->name('update');
        Route::delete('{answer}', 'ExamQuestionsController@destroy_answer')->name('delete_answer');
        Route::post('store', 'ExamQuestionsController@store')->name('store');
        Route::get('{exam}/create', 'ExamQuestionsController@create')->name('create');
        Route::post('remove', 'ExamQuestionsController@remove')->name('remove_img');
    });


    //======================================//
    //======= Exam Sections Routes =========//
    //======================================//
    Route::prefix('exam_sections')->name('admin.exam_sections.')->middleware('admin.user')->group(function() {
        Route::get('{exam}/show', 'ExamSectionsController@show')->name('show');
        Route::get('{section}/edit', 'ExamSectionsController@edit')->name('edit');
        Route::get('{exam}/create', 'ExamSectionsController@create')->name('create');
        Route::post('{exam}', 'ExamSectionsController@store')->name('store');
        Route::put('{section}', 'ExamSectionsController@update')->name('update');
        Route::delete('{section}', 'ExamSectionsController@destroy')->name('delete');
    });
});

Route::get('/', 'HomeController@index')->name('home');
Route::get('about-us', 'HomeController@about')->name('about');
Route::get('contact', 'HomeController@show_contact')->name('contact');
Route::post('contact', 'HomeController@contact');
Route::get('pages/{page}', 'HomeController@pages')->name('pages');

//======================================//
//========= Qeyas News Routes ==========//
//======================================//
Route::prefix('news')->name('news.')->group(function() {
    Route::get('/', 'NewsController@index')->name('index');
    Route::get('{news}/show', 'NewsController@show')->name('show');
});


//======================================//
//========= Categories Routes ==========//
//======================================//
Route::prefix('categories')->name('categories.')->group(function() {
    Route::get('/', 'CategoriesController@index')->name('index');
    Route::get('{category}/show', 'CategoriesController@show')->name('show');
});

//======================================//
//============ Exam Routes =============//
//======================================//
Route::prefix('exams')->name('exams.')->group(function() {
    Route::get('/', 'ExamsController@index')->name('index');
    Route::get('{exam}/toplist', 'ExamsController@toplist')->name('toplist');
    Route::get('search', 'ExamsController@search')->name('search');
    Route::middleware('auth')->group(function(){
        Route::get('{exam}/show', 'ExamsController@show')->name('show');
        Route::get('{exam}/start', 'ExamsController@start')->name('start');
        Route::get('{exam}/buy', 'ExamsController@buy')->name('buy');
        Route::post('finish', 'ExamsController@post_exam')->name('post_exam');
        Route::get('{report}/report', 'ExamsController@report')->name('report');
        Route::get('/paypal/checkout', 'PayPalController@checkout_exam')
            ->name('checkout');
        Route::get('/paypal/checkout/success', 'PayPalController@checkout_exam_success')
            ->name('checkout_success');
    });

});

//======================================//
//============ User Routes =============//
//======================================//
Route::prefix('user')->name('user.')->middleware('auth')->group(function() {
    Route::get('profile', 'UserController@profile')->name('profile');
    Route::get('profile/edit', 'UserController@edit')->name('edit-profile');
    Route::post('profile', 'UserController@update')->name('update-profile');
    Route::post('update_password', 'UserController@update_password')->name('update_password');
    Route::get('notifications', 'UserController@notifications')->name('notifications');
});

//======================================//
//=========== Courses Routes ===========//
//======================================//
Route::prefix('courses')->name('courses.')->group(function() {
    Route::get('/', 'CoursesController@index')->name('index');
    Route::get('/{course}/show', 'CoursesController@show')->name('show');
    Route::get('search', 'CoursesController@search')->name('search');
    Route::post('{course}/request', 'CoursesController@request')
        ->middleware('auth')
        ->name('request');
});

//======================================//
//=========== Books Routes ===========//
//======================================//
Route::prefix('books')->name('books.')->group(function() {
    Route::get('/', 'BooksController@index')->name('index');
    Route::get('{book}/show', 'BooksController@show')->name('show');
    Route::middleware('auth')->group(function() {
        Route::get('{book}/view', 'BooksController@view')->name('view');
        Route::get('{book}/download', 'BooksController@download')->name('download');
        Route::get('{book}/buy', 'BooksController@buy')->name('buy');
        Route::get('paypal/checkout', 'PayPalController@checkout_book')
            ->name('checkout');
        Route::get('paypal/checkout/success', 'PayPalController@checkout_book_success')
            ->name('checkout_success');
    });
});

//======================================//
//=========== Videos Routes ===========//
//======================================//
Route::prefix('videos')->name('videos.')->group(function() {
    Route::get('/', 'VideosController@index')->name('index');
    Route::get('{video}/show', 'VideosController@show')->name('show');
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * App\Category
 *
 * @property int $cat_id
 * @property string|null $cat_name
 * @property int $cat_parent
 * @property int $cat_order
 * @property int $cat_app_order
 * @property string|null $cat_image
 * @property int $cat_author_id
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Category newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Category newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Category query()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Category whereCatAppOrder($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Category whereCatAuthorId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Category whereCatId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Category whereCatImage($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Category whereCatName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Category whereCatOrder($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Category whereCatParent($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Category whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Category whereUpdatedAt($value)
 * @mixin \Eloquent
 */
class Category extends Model
{
    protected static function boot() {
        parent::boot();
        self::creating(function($model){
            if(is_null(request('cat_parent'))){
                $model->cat_parent = 0;
            }
            if(is_null(request('cat_author_id'))){
                $model->cat_author_id = \Auth::id();
            }
        });
        self::updating(function($model){
            if(is_null(request('cat_parent'))){
                $model->cat_parent = 0;
            }
            if(is_null(request('cat_author_id'))){
                $model->cat_author_id = \Auth::id();
            }
        });
    }

    public function exams_count($id)
    {
        $ids = [];

        $sub_cats = Category::where('cat_parent', $id)->pluck('id');

        foreach($sub_cats as $sub)
        {
            array_push($ids,$sub);
            $secondaries = Category::where('cat_parent', $sub)->pluck('id');

            foreach($secondaries as $sec)
            {
                array_push($ids,$sec);
            }
        }

        $count = Exam::whereIn('category_id',$ids)->count();

        return $count;
    }

    public function get_exams_count($id)
    {
        $count = Exam::where('category_id',$id)->count();
        return $count;
    }

    public function is_last($id)
    {
        $subs = Category::where('cat_parent', $id)->count();

        if($subs > 0) return false;
        else return true;
    }

    public function sub_categories() {
        return $this->hasMany(self::class, 'cat_parent', 'id');
    }

    public function parent_category() {
        return $this->belongsTo(self::class, 'cat_parent', 'id');
    }

    public function exams() {
        return $this->hasMany(Exam::class);
    }

    public function getCatImageApiAttribute($value)
    {
        return $value != NULL ? $_SERVER['APP_URL'].'/storage/'.$value : '';
    }

    public function is_parent() {
        return (bool) $this->sub_categories()->count();
    }

    public function exam_count() {
        $count = 0;
        $count += $this->exams->count();
        if($this->is_parent()){
            foreach($this->sub_categories as $sub_category) {
                $count += $sub_category->exam_count();
            }
        }
        return $count;
    }
}

app/Http/Controllers/CategoriesController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use Illuminate\Http\Request;

class CategoriesController extends Controller
{

    public function index() {
        $all_categories = Category::whereCatParent(0)->paginate(5);
        $title = 'أقسام الاختبارات';
        return view('categories.index', compact('all_categories', 'title'));
    }

    public function show(Category $category) {
        $title = $category->cat_name;
        if($category->is_parent()){
            return view('categories.index', compact('category', 'title'));
        }
        return view('categories.show', compact('category', 'title'));
    }
}

resources/views/categories/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="banner inner-page">
        <div class="banner-img">
            <img src="{{ asset('images/banner/register-bannerImg.jpg') }}" alt="">
        </div>
        <div class="page-title">
            <div class="container">
                <h1 class="Tajawal-font">الأقسام الرئيسية للإختبارات</h1>
            </div>
        </div>
    </section>
    <section class="breadcrumb">
        <div class="container">
            <ul>
                <li><a href="{{ route('home') }}">الرئيسية</a></li>
                <li><a href="{{ route('categories.index') }}">الأقسام الرئيسية للإختبارات</a></li>
            </ul>
        </div>
    </section>
    <section class="courses-view list-view">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="group-tab-view">
                        <div class="forum-details">
                            @if(isset($all_categories) && $all_categories->count())
                                @foreach($all_categories as $category)
                                    @if($category->exam_count() == 0)
                                        @continue
                                    @endif
                                    <div class="details-slide {{ $loop->index % 2 == 0 ? 'even' : '' }}">
                                        <div class="name">
                                            <img src="{{ asset('images/user-img/test.png') }}" alt="">
                                            <div class="Tajawal-font fontsize-18">{{ $category->cat_name }}</div>
                                        </div>
                                        @foreach($category->sub_categories as $cat)
                                            @if($cat->exam_count() == 0)
                                                @continue
                                            @endif
                                            <div class="info">
                                                <div class="block fontsize-18">
                                                    <a href="{{ route('categories.show', $cat->id) }}">
                                                        {{ $cat->cat_name }}
                                                    </a>
                                                </div>
                                                <div class="block">{{ $cat->exam_count() }} إختبار</div>
                                            </div>
                                        @endforeach
                                    </div>
                                @endforeach
                            @elseif(isset($category))
                                <div class="details-slide">
                                    <div class="name">
                                        <img src="{{ asset('images/user-img/test.png') }}" alt="">
                                        <div class="Tajawal-font fontsize-18">{{ $category->cat_name }}</div>
                                    </div>
                                    @foreach($category->sub_categories as $cat)
                                        @if($cat->exam_count() == 0)
                                            @continue
                                        @endif
                                        <div class="info">
                                            <div class="block fontsize-18">
                                                <a href="{{ route('categories.show', $cat->id) }}">
                                                    {{ $cat->cat_name }}
                                                </a>
                                            </div>
                                            <div class="block">{{ $cat->exams->count() }} إختبار</div>
                                        </div>
                                    @endforeach
                                </div>
                            @endif
                        </div>
                        @if(isset($all_categories))
                            {{ $all_categories->links() }}
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/categories/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="banner inner-page">
        <div class="banner-img"><img src="{{ asset('images/banner/register-bannerImg.jpg') }}" alt=""></div>
        <div class="page-title">
            <div class="container">
                <h1 class="Tajawal-font">إختبارات قياس</h1>
            </div>
        </div>
    </section>
    <section class="breadcrumb">
        <div class="container">
            <ul>
                <li><a href="{{ route('home') }}">الرئيسية</a></li>
                <li><a href="{{ route('exams.index') }}">إختبارات قياس</a></li>
                <li>{{ $category->cat_name }}</li>
            </ul>
        </div>
    </section>
    <section class="courses-view list-view">
        <div class="container">
            @if($category->exam_count())
                <div class="row">
                    <div class="col-md-3 hidden-sm hidden-xs">
                        <div class="right-slide left">
                            <form action="{{ route('exams.search') }}" method="get">
                                <h3 class="Tajawal-font">نوع الإختبار</h3>
                                <div class="filter-blcok">
                                    <div class="check-slide">
                                        <label class="label_check" for="exam_type_free">
                                            <input id="exam_type_free" type="checkbox" name="free_exam" value="1"> مجاني
                                        </label>
                                    </div>
                                    <div class="check-slide">
                                        <label class="label_check" for="exam_type_paid">
                                            <input id="exam_type_paid" type="checkbox" name="paid_exam" value="1"> مدفوع
                                        </label>
                                    </div>
                                </div>
                                {{--<h3 class="Tajawal-font">اللغة</h3>--}}
                                {{--<div class="filter-blcok">--}}
                                {{--<div class="check-slide">--}}
                                {{--<label class="label_check" for="checkbox-03"><input id="checkbox-03" type="checkbox"> العربية</label>--}}
                                {{--</div>--}}
                                {{--<div class="check-slide">--}}
                                {{--<label class="label_check" for="checkbox-04"><input id="checkbox-04" type="checkbox"> الإنجليزية</label>--}}
                                {{--</div>--}}
                                {{--</div>--}}
                                <h3 class="Tajawal-font">أقسام الإختبارات</h3>
                                <div class="filter-blcok">
                                    @foreach($categories as $cat)
                                        <div class="check-slide">
                                            <label class="label_check" for="checkbox-{{ $loop->index }}">
                                                <input id="checkbox-{{ $loop->index }}" type="checkbox"
                                                       name="categories[]"
                                                       value="{{ $cat->id }}">
                                                {{ $cat->cat_name }}
                                            </label>
                                        </div>
                                    @endforeach
                                </div>
                                <h3 class="Tajawal-font">متوسط السعر</h3>
                                <div class="filter-blcok">
                                    <div class="form-group">
                                        <input type="number" name="from_price" class="form-control" placeholder="السعر من">
                                    </div>
                                    <div class="form-group">
                                        <input type="number" name="to_price" class="form-control" placeholder="السعر إلى">
                                    </div>
                                    <button type="submit" class="btn" name="button">بحث</button>
                                </div>
                            </form>
                        </div>
                    </div>
                    <div class="col-md-9">
                        <div class="filter-row">
                            <div class="search">
                                <form action="{{ route('exams.search') }}" method="get">
                                    <input type="text" name="q" placeholder="Search">
                                    <input type="submit" value="">
                                </form>
                            </div>
                        </div>
                        @foreach($category->exams()->paginate(10) as $exam)
                            <div class="test-page">
                                <div class="event-box">
                                    @if(Auth::check() && ! Auth::user()->is_admin())
                                        @if($exam->is_paid() && Auth::user()->has_exam($exam->id))
                                            <div class="price">
                                                <i class="fa fa-star" aria-hidden="true"></i>
                                                <span class="Tajawal-font">تم الشراء</span>
                                            </div>
                                        @endif
                                    @endif
                                    <div class="event-name">
                                        <a href="{{ route('exams.show', $exam) }}">
                                            {{ $exam->title }}
                                        </a>
                                    </div>
                                    <div class="event-info">
                                        <i class="fa fa-clock-o"></i>
                                        {{ $exam->exam_duration }} دقيقة
                                    </div>
                                    <div class="event-info">
                                        <i class="fa fa-question-circle-o" aria-hidden="true"></i>
                                        {{ $exam->questions->count() }} سؤال / أسئلة
                                    </div>
                                    <div class="event-info">
                                        <i class="fa fa-money" aria-hidden="true"></i>
                                        {{ $exam->is_paid() ? 'مدفوع' : 'مجاني' }}
                                    </div>
                                    @if($exam->is_paid())
                                        <div class="event-info">
                                            <i class="fa fa-money" aria-hidden="true"></i>
                                            {{ $exam->exam_price }}
                                        </div>
                                    @endif
                                    <a href="{{ route('exams.toplist', $exam) }}" class="btn toplist-btn">قائمة الأفضل</a>
                                </div>
                            </div>
                        @endforeach
                    </div>
                    {{ $category->exams()->paginate(10)->links() }}
                </div>
            @else
                <div class="alert alert-info">
                    لا توجد اختبارات في هذا التصنيف
                </div>
            @endif
        </div>
    </section>
@endsection