routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
//======================================//
//========= Social Login Routes ========//
//======================================//
Route::get('auth/{social}', 'SocialLoginController@redirectToProvider')->name('social_login');
Route::get('auth/{social}/callback', 'SocialLoginController@handleProviderCallback');


Route::get('artisan', function() {
    Artisan::call('route:list');
    dd(Artisan::output());
});
Route::group(['prefix' => 'admin'], function() {
    Voyager::routes();

    //======================================//
    //==== Exam Question & Answers Routes ===//
    //======================================//
    Route::prefix('exam_questions')->name('admin.exam_questions.')->middleware('admin.user')->group(function() {
        Route::get('{exam}/show', 'ExamQuestionsController@show')->name('show');
        Route::delete('{question}/delete', 'ExamQuestionsController@destroy')->name('delete');
        Route::get('{question}/edit', 'ExamQuestionsController@edit')->name('edit');
        Route::put('{question}', 'ExamQuestionsController@update')->name('update');
        Route::delete('{answer}', 'ExamQuestionsController@destroy_answer')->name('delete_answer');
        Route::post('store', 'ExamQuestionsController@store')->name('store');
        Route::get('{exam}/create', 'ExamQuestionsController@create')->name('create');
        Route::post('remove', 'ExamQuestionsController@remove')->name('remove_img');
    });


    //======================================//
    //======= Exam Sections Routes =========//
    //======================================//
    Route::prefix('exam_sections')->name('admin.exam_sections.')->middleware('admin.user')->group(function() {
        Route::get('{exam}/show', 'ExamSectionsController@show')->name('show');
        Route::get('{section}/edit', 'ExamSectionsController@edit')->name('edit');
        Route::get('{exam}/create', 'ExamSectionsController@create')->name('create');
        Route::post('{exam}', 'ExamSectionsController@store')->name('store');
        Route::put('{section}', 'ExamSectionsController@update')->name('update');
        Route::delete('{section}', 'ExamSectionsController@destroy')->name('delete');
    });
});

Route::get('/', 'HomeController@index')->name('home');
Route::get('about-us', 'HomeController@about')->name('about');
Route::get('contact', 'HomeController@show_contact')->name('contact');
Route::post('contact', 'HomeController@contact');
Route::get('pages/{page}', 'HomeController@pages')->name('pages');

//======================================//
//========= Qeyas News Routes ==========//
//======================================//
Route::prefix('news')->name('news.')->group(function() {
    Route::get('/', 'NewsController@index')->name('index');
    Route::get('{news}/show', 'NewsController@show')->name('show');
});


//======================================//
//========= Categories Routes ==========//
//======================================//
Route::prefix('categories')->name('categories.')->group(function() {
    Route::get('/', 'CategoriesController@index')->name('index');
    Route::get('{category}/show', 'CategoriesController@show')->name('show');
});

//======================================//
//============ Exam Routes =============//
//======================================//
Route::prefix('exams')->name('exams.')->group(function() {
    Route::get('/', 'ExamsController@index')->name('index');
    Route::get('{exam}/toplist', 'ExamsController@toplist')->name('toplist');
    Route::get('search', 'ExamsController@search')->name('search');
    Route::middleware('auth')->group(function(){
        Route::get('{exam}/show', 'ExamsController@show')->name('show');
        Route::get('{exam}/start', 'ExamsController@start')->name('start');
        Route::get('{exam}/buy', 'ExamsController@buy')->name('buy');
        Route::post('finish', 'ExamsController@post_exam')->name('post_exam');
        Route::get('{report}/report', 'ExamsController@report')->name('report');
        Route::get('/paypal/checkout', 'PayPalController@checkout_exam')
            ->name('checkout');
        Route::get('/paypal/checkout/success', 'PayPalController@checkout_exam_success')
            ->name('checkout_success');
    });

});

//======================================//
//============ User Routes =============//
//======================================//
Route::prefix('user')->name('user.')->middleware('auth')->group(function() {
    Route::get('profile', 'UserController@profile')->name('profile');
    Route::get('profile/edit', 'UserController@edit')->name('edit-profile');
    Route::post('profile', 'UserController@update')->name('update-profile');
    Route::post('update_password', 'UserController@update_password')->name('update_password');
    Route::get('notifications', 'UserController@notifications')->name('notifications');
});

//======================================//
//=========== Courses Routes ===========//
//======================================//
Route::prefix('courses')->name('courses.')->group(function() {
    Route::get('/', 'CoursesController@index')->name('index');
    Route::get('/{course}/show', 'CoursesController@show')->name('show');
    Route::get('search', 'CoursesController@search')->name('search');
    Route::post('{course}/request', 'CoursesController@request')
        ->middleware('auth')
        ->name('request');
});

//======================================//
//=========== Books Routes ===========//
//======================================//
Route::prefix('books')->name('books.')->group(function() {
    Route::get('/', 'BooksController@index')->name('index');
    Route::get('{book}/show', 'BooksController@show')->name('show');
    Route::middleware('auth')->group(function() {
        Route::get('{book}/view', 'BooksController@view')->name('view');
        Route::get('{book}/download', 'BooksController@download')->name('download');
        Route::get('{book}/buy', 'BooksController@buy')->name('buy');
        Route::get('paypal/checkout', 'PayPalController@checkout_book')
            ->name('checkout');
        Route::get('paypal/checkout/success', 'PayPalController@checkout_book_success')
            ->name('checkout_success');
    });
});

//======================================//
//=========== Videos Routes ===========//
//======================================//
Route::prefix('videos')->name('videos.')->group(function() {
    Route::get('/', 'VideosController@index')->name('index');
    Route::get('{video}/show', 'VideosController@show')->name('show');
});

app/Question.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * App\Question
 *
 * @property int $id
 * @property int $exam_id
 * @property string $question
 * @property int|null $right_answer_id
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Question newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Question newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Question query()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Question whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Question whereExamId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Question whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Question whereQuestion($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Question whereRightAnswerId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Question whereUpdatedAt($value)
 * @mixin \Eloquent
 */
class Question extends Model
{
    protected $table = 'exam_questions';


    public function getImageApiAttribute($value)
    {
        if($value != NULL) return $_SERVER['APP_URL'].'/storage/'.$value;
        else return '';
    }


    public function getParagraphAttribute($value)
    {
        if($value != NULL) return $value;
        else return '';
    }


    public function get_section($section_id)
    {
        $section = ExamSection::find($section_id);
        return $section->section_title;
    }


    public function get_answers($question_id)
    {
        $answers = Answer::where('question_id', $question_id)->select('id','option_text as text','option_img as image_api')->get();

        foreach($answers as $answer)
        {
            $a_no_tags = strip_tags($answer->text,'<p>');
            $answer['a_html'] = ($answer->text != $a_no_tags) ? true : false ;
        }

        return $answers;
    }
}

app/Http/Controllers/ExamsController.php
<?php

namespace App\Http\Controllers;

use App\Exam;
use App\ExamQuestion;
use App\ExamReport;
use App\ExamTry;
use App\UserAnswer;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Auth;

class ExamsController extends Controller
{

    public function index() {
        $exams = Exam::where('available', 1)->paginate(10);
        $title = 'جميع الاختبارات';
        return view('exams.index', compact('exams', 'title'));
    }

    public function show(Exam $exam) {
        if(! $exam->available) {
            abort(401, 'هذا الاختبار غير متاح في الوقت الحالي');
        }
        if($exam->exam_type == 'paid' && ! Auth::user()->has_exam($exam->id)) {
            return redirect()->route('exams.buy', $exam);
        }

        $title = $exam->title;
        return view('exams.show', compact('exam', 'title'));
    }

    public function buy(Exam $exam) {
        if(! $exam->available) {
            abort(401, 'هذا الاختبار غير متاح في الوقت الحالي');
        }
        if($exam->exam_type == 'free' || Auth::user()->has_exam($exam->id)) {
            return redirect()->route('exams.show', $exam);
        }
        $title = 'شراء اختبار';
        return view('exams.buy', compact('exam', 'title'));
    }

    public function start(Exam $exam) {
        $title = $exam->title;
        $sections = $exam->sections;
        return view('exams.start', compact('exam', 'title', 'sections'));
    }

    public function post_exam(Request $request) {
        $exam = Exam::find($request->exam_id);
        if($request->userSubmit) {
            if(! isset($request->questions) || count($request->questions) < $exam->questions->count()) {
                return back()->withErrors('يجب الاجابة على جميع الاسئلة لانهاء الاختبار');
            }
        }
        $right_answers = 0;
        $wrong_answers = 0;

//        dd($request->all());
        if(! is_null($request->questions)) {


            foreach($request->questions as $question => $answer) {
                $_question = ExamQuestion::find($question);
                $user_answer = $answer;
                $right_answer = $_question->right_answer_id;
                if($user_answer == $right_answer) {
                    $right_answers++;
                } else {
                    $wrong_answers++;
                }
            }
            $time_spent = gmdate('H:i:s', $request->time_spent);
            $percentage = ceil(($right_answers / $exam->questions->count()) * 100);
            $try = new ExamTry;
            $try->exam_id = $exam->id;
            $try->user_id = Auth::id();
            $try->result = $right_answers . '/' . $exam->questions->count();
            $try->percentage = $percentage;
            $try->time_spent = $time_spent;
            $try->num_passed_questions = $right_answers;
            $try->num_failed_questions = $wrong_answers;
            $try->save();


            foreach($request->questions as $q => $a) {
                $user_answers = new UserAnswer;
                $user_answers->exam_try_id = $try->id;
                $user_answers->user_id = Auth::id();
                $user_answers->question_id = $q;
                $user_answers->answer_id = $a;
                $user_answers->right_answer_id = ExamQuestion::find($q)->right_answer_id;
                $user_answers->save();
            }

            $exam_report = ExamReport::where('exam_id', $exam->id)->where('user_id', \Auth::id())->first();
            $report = $exam_report ?? new ExamReport;
            $report->num_tries++;
            $report->exam_id = $exam->id;
            $report->user_id = Auth::id();
            $report->highest_result = $report->highest_result > $percentage ? $report->highest_result : "$percentage%";
            $report->last_try_date = Carbon::now();
            $report->time_spent = $time_spent;
            $report->save();

            return view('exams.result', compact(
                'exam',
                'time_spent',
                'percentage',
                'wrong_answers',
                'right_answers'
            ));
        }
        return view('exams.failed', compact('exam'));
    }

    public function toplist(Exam $exam) {
        $title = 'قائمة الافضل';
        $top_students = $exam->reports()->orderBy('highest_result', 'desc')->take(10)->get();
        return view('exams.toplist', compact('title', 'top_students', 'exam'));
    }

    public function report(ExamReport $report) {
        $tries = ExamTry::where('exam_id', $report->exam_id)->where('user_id', Auth::id())->get();
        return view('exams.report', compact('report', 'tries'));
    }

    public function search(Request $request) {
        $exams = new Exam;
//        if(isset($request->exam_type)){
//            $exams = $exams->whereIn('exam_type', $request->exam_type);
//        }
        if($request->free_exam == 1) {
            $exams = $exams->where('exam_type', 'free')->orWhere('exam_price', 0);
        }
        if($request->paid_exam == 1) {
            $exams = $exams->where('exam_type', 'paid')->orWhere('exam_price', '!=', 0);
        }
        if(isset($request->categories)){
            $exams = $exams->whereIn('category_id', $request->categories);
        }
        if(isset($request->from_price)){
            $exams = $exams->where('exam_price', '>=', $request->from_price);
        }
        if(isset($request->to_price)){
            $exams = $exams->where('exam_price', '<=', $request->to_price);
        }
        if(isset($request->q)){
            $exams = $exams->where('title', 'like', "%$request->q%");
        }
        $exams = $exams->paginate(10);

        return view('exams.search', compact('exams'));
    }
}

resources/views/exams/failed.blade.php
@extends('layouts.app')

@section('content')
    <section class="banner inner-page">
        <div class="banner-img"><img src="{{ asset('images/banner/register-bannerImg.jpg') }}" alt=""></div>
        <div class="page-title">
            <div class="container">
                <h1 class="Tajawal-font">نتيجة الاختبار</h1>
            </div>
        </div>
    </section>
    <section class="breadcrumb">
        <div class="container">
            <ul>
                <li><a href="{{ route('home') }}">الرئيسية</a></li>
                <li><a href="{{ route('exams.show', $exam) }}">تعليمات قبل الاختبار</a></li>
                {{--<li><a href="quiz.html">الاختبار</a></li>--}}
                <li>نتيجة الإختبار</li>
            </ul>
        </div>
    </section>
    <section class="quiz-view">
        <div class="container">
            <div class="result-msg">
                <h2 class="Tajawal-font">خطأ!</h2>
                <p class="alert alert-danger">لم يتم الاجابة على اي سؤال .. من فضلك <a href="{{ route('exams.start', $exam) }}">اعد المحاولة</a></p>
            </div>
        </div>
    </section>
@endsection

resources/views/exams/start.blade.php
@extends('layouts.app')

@section('content')

    <section class="banner inner-page">
        <div class="banner-img"><img src="{{ asset('images/banner/register-bannerImg.jpg') }}" alt=""></div>
        <div class="page-title">
            <div class="container">
                <h1 class="Tajawal-font">{{ $exam->title }}</h1>
            </div>
        </div>
    </section>
    <section class="breadcrumb">
        <div class="container">
            <ul>
                <li><a href="{{ route('categories.show', $exam->category) }}">القسم الفرعي</a></li>
                <li><a href="{{ route('exams.show', $exam) }}">تعليمات قبل الاختبار</a></li>
                <li>{{ $exam->title }}</li>
            </ul>
        </div>
    </section>
    <section class="quiz-view">
        <div class="container">
            <div class="row">
                <div class="col-sm-4 col-md-3">
                    <div id="countdown" style="direction: ltr"></div>
                    <div class="qustion-list">
                        @foreach($sections as $section)
                            @if($section->questions->count())
                                <div class="qustion-slide" id="section-{{ $loop->index + 1 }}-title">
                                    <div class="qustion-number">{{ $section->section_title }}</div>
                                    <span>{{ $section->questions->count() }}</span>
                                </div>
                            @endif
                        @endforeach
                    </div>
                </div>
                <!-- has class exam_en or exam_ar based on exam language -->
                <div class="col-sm-8 col-md-9 exam_{{ $exam->lang }}">
                    @if(count($errors->all()))
                        <div class="alert alert-danger">
                            <ul>
                                @foreach($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    <form action="{{ route('exams.post_exam') }}" method="post" id="exam-from">
                        {{ csrf_field() }}
                        <input type="hidden" name="exam_id" value="{{ $exam->id }}">
                        <input type="hidden" name="userSubmit" id="user_submit" value=0>
                        <input type="hidden" name="time_spent" id="time_spent">
                        <div class="qustion-main" id="questions">
                            <div class="qustion-box" id="question-box">
                                @foreach($sections as $section)
                                    @if($section->questions->count())
                                        <div class="sections" id="section-{{ $loop->index + 1 }}">
                                            <div class="fontsize-18" style="margin-bottom: 10px;">
                                                <b>{{ $section->section_title }}</b>
                                            </div>
                                            @foreach($section->questions as $question)

                                                <div class="qustion">
                                                    {{ switch_numbers(($loop->index+1), $exam->lang) }}
                                                    @if(isset($question->question_text))
                                                        {!! switch_numbers($question->question_text, $exam->lang) !!}
                                                    @endif
                                                    @if(isset($question->question_image))
                                                        <img class="q-img"
                                                             src="{{ Voyager::image($question->question_img, asset('images/blog/img1.jpg')) }}"
                                                             alt="">
                                                    @endif
                                                </div>
                                                @if(isset($question->paragraph))
                                                <!-- Button trigger modal -->
                                                    <div style="margin-top: 10px;">
                                                        <button type="button" class="btn" data-toggle="modal" data-target="#paragraph-{{ $question->id }}">
                                                            القطعة
                                                        </button>
                                                    </div>

                                                    <!-- Modal -->
                                                    <div class="modal fade" id="paragraph-{{ $question->id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                                                        <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
                                                            <div class="modal-content">
                                                                <div class="modal-header">
                                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                                        <span aria-hidden="true">&times;</span>
                                                                    </button>
                                                                </div>
                                                                <div class="modal-body">
                                                                    @if($exam->lang == 'ar')
                                                                        {!! switch_numbers($question->paragraph, $exam->lang) !!}
                                                                    @else
                                                                    @endif
                                                                </div>
                                                                {{--<div class="modal-footer">--}}
                                                                {{--<button type="button" class="btn btn-secondary pull-right" data-dismiss="modal">إغلاق</button>--}}
                                                                {{--</div>--}}
                                                            </div>
                                                        </div>
                                                    </div>
                                                @endif
                                                <div class="ans">
                                                    @foreach($question->options as $option)
                                                        <div class="ans-slide">
                                                            @php($lang = $exam->lang)
                                                            {{ ${'list_index_' . $exam->lang}[$loop->index + 1] }} -
                                                            <label class="label_radio" for="radio-{{ $option->id }}">
                                                                <input name="questions[{{ $question->id }}]answer" id="radio-{{ $option->id }}" value="{{ $option->id }}" type="radio" {{ old("radio-". $option->id) ? 'checked' : '' }}>
                                                                @if(isset($option->option_text))
                                                                    {!! switch_numbers($option->option_text, $exam->lang) !!}
                                                                @endif
                                                                @if(isset($option->option_img))
                                                                    <img src="{{ Voyager::image($option->option_img, asset('images/certificate-logo.jpg')) }}" alt="">
                                                                @endif
                                                            </label>
                                                        </div>
                                                    @endforeach
                                                </div>
                                                <hr style="border:2px dashed gray">
                                            @endforeach
                                        </div>
                                    @endif
                                @endforeach
                                <div class="btn-slide" id="pagination">
                                    <a href="javascript:" class="btn" id="previous">
                                        <i class="fa fa-angle-right"></i>
                                    </a>
                                    <a href="javascript:" class="btn" id="next">
                                        <i class="fa fa-angle-left"></i>
                                    </a>
                                </div>
                                <div class="submit-quiz">
                                    <button type="submit" class="btn" id="submit">إنهاء الإختبار</button>
                                </div>

                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
@endsection
@section('scripts')
    <script type="text/javascript" src="{{ asset('js/jquery.countdown.js') }}"></script>
    <script>
        let minutes = parseInt("{{ $exam->exam_duration }}");
        let time_start = new Date().getTime();

        $('#countdown').countdown({
            timestamp: new Date().getTime() + minutes * 60 * 1000,
            callback: function () {
                let now = new Date().getTime();
                if (now > this.timestamp) {
                    alert('تم انتهاء الوقت');
                    $('#exam-from').submit();
                    this.stopeed = true;
                }
            },
            stopeed: false
        });

        $(function () {
            // Check if the form submitted by user or by javascript
            $('#submit').on('click', function (e) {
                $('#user_submit').val(1);
            });

            let page = 1;
            let sections = $('.sections');
            let prev = $('#previous');
            let next = $('#next');

            // Add style classes to sections' labels
            function addFillClass() {
                for (let i = 1; i < page; i++) {
                    $('#section-' + i + '-title').addClass('fill');
                }
            }

            function addActiveClass(page) {
                $('#section-' + page + '-title').addClass('active');
            }

            // show/hide paragraph (if exist)
            $('body').on('click', '.toggleParagraph', function () {
                let id = $(this).data('id');
                let paragraph = $('#paragraph-' + id);
                paragraph.toggleClass('hidden');
                if (paragraph.hasClass('hidden')) {
                    $(this).text('اظهار القطعة');
                } else {
                    $(this).text('اخفاء القطعة');
                }
            });

            function hideSections() {
                sections.each(function (index, section) {
                    $(section).hide();
                    if ($('.sections#section-' + page).length) {
                        $('#section-' + page).fadeIn();
                    }
                });
            }

            // show/hide sections
            hideSections();
            addFillClass();
            addActiveClass(page);
            prev.hide();
            next.on('click', function () {
                page++;
                addActiveClass(page);
                prev.show();
                hideSections();
                addFillClass();
                if (page >= sections.length) {
                    $(this).hide();
                }
            });

            prev.on('click', function () {
                page--;
                next.show();
                hideSections();
                addFillClass();
                if (page <= 1) {
                    $(this).hide();
                }
            });

            // submit the form if time end
            $('form#exam-from').submit(function () {
                let time_end = new Date().getTime();
                let time_spent = (time_end - time_start) / 1000;
                $('#time_spent').val(time_spent);
            });
        });

    </script>
@endsection