routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
//======================================//
//========= Social Login Routes ========//
//======================================//
Route::get('auth/{social}', 'SocialLoginController@redirectToProvider')->name('social_login');
Route::get('auth/{social}/callback', 'SocialLoginController@handleProviderCallback');


Route::get('artisan', function() {
    Artisan::call('route:list');
    dd(Artisan::output());
});
Route::group(['prefix' => 'admin'], function() {
    Voyager::routes();

    //======================================//
    //==== Exam Question & Answers Routes ===//
    //======================================//
    Route::prefix('exam_questions')->name('admin.exam_questions.')->middleware('admin.user')->group(function() {
        Route::get('{exam}/show', 'ExamQuestionsController@show')->name('show');
        Route::delete('{question}/delete', 'ExamQuestionsController@destroy')->name('delete');
        Route::get('{question}/edit', 'ExamQuestionsController@edit')->name('edit');
        Route::put('{question}', 'ExamQuestionsController@update')->name('update');
        Route::delete('{answer}', 'ExamQuestionsController@destroy_answer')->name('delete_answer');
        Route::post('store', 'ExamQuestionsController@store')->name('store');
        Route::get('{exam}/create', 'ExamQuestionsController@create')->name('create');
        Route::post('remove', 'ExamQuestionsController@remove')->name('remove_img');
    });


    //======================================//
    //======= Exam Sections Routes =========//
    //======================================//
    Route::prefix('exam_sections')->name('admin.exam_sections.')->middleware('admin.user')->group(function() {
        Route::get('{exam}/show', 'ExamSectionsController@show')->name('show');
        Route::get('{section}/edit', 'ExamSectionsController@edit')->name('edit');
        Route::get('{exam}/create', 'ExamSectionsController@create')->name('create');
        Route::post('{exam}', 'ExamSectionsController@store')->name('store');
        Route::put('{section}', 'ExamSectionsController@update')->name('update');
        Route::delete('{section}', 'ExamSectionsController@destroy')->name('delete');
    });
});

Route::get('/', 'HomeController@index')->name('home');
Route::get('about-us', 'HomeController@about')->name('about');
Route::get('contact', 'HomeController@show_contact')->name('contact');
Route::post('contact', 'HomeController@contact');
Route::get('pages/{page}', 'HomeController@pages')->name('pages');

//======================================//
//========= Qeyas News Routes ==========//
//======================================//
Route::prefix('news')->name('news.')->group(function() {
    Route::get('/', 'NewsController@index')->name('index');
    Route::get('{news}/show', 'NewsController@show')->name('show');
});


//======================================//
//========= Categories Routes ==========//
//======================================//
Route::prefix('categories')->name('categories.')->group(function() {
    Route::get('/', 'CategoriesController@index')->name('index');
    Route::get('{category}/show', 'CategoriesController@show')->name('show');
});

//======================================//
//============ Exam Routes =============//
//======================================//
Route::prefix('exams')->name('exams.')->group(function() {
    Route::get('/', 'ExamsController@index')->name('index');
    Route::get('{exam}/toplist', 'ExamsController@toplist')->name('toplist');
    Route::get('search', 'ExamsController@search')->name('search');
    Route::middleware('auth')->group(function(){
        Route::get('{exam}/show', 'ExamsController@show')->name('show');
        Route::get('{exam}/start', 'ExamsController@start')->name('start');
        Route::get('{exam}/buy', 'ExamsController@buy')->name('buy');
        Route::post('finish', 'ExamsController@post_exam')->name('post_exam');
        Route::get('{report}/report', 'ExamsController@report')->name('report');
        Route::get('/paypal/checkout', 'PayPalController@checkout_exam')
            ->name('checkout');
        Route::get('/paypal/checkout/success', 'PayPalController@checkout_exam_success')
            ->name('checkout_success');
    });

});

//======================================//
//============ User Routes =============//
//======================================//
Route::prefix('user')->name('user.')->middleware('auth')->group(function() {
    Route::get('profile', 'UserController@profile')->name('profile');
    Route::get('profile/edit', 'UserController@edit')->name('edit-profile');
    Route::post('profile', 'UserController@update')->name('update-profile');
    Route::post('update_password', 'UserController@update_password')->name('update_password');
    Route::get('notifications', 'UserController@notifications')->name('notifications');
});

//======================================//
//=========== Courses Routes ===========//
//======================================//
Route::prefix('courses')->name('courses.')->group(function() {
    Route::get('/', 'CoursesController@index')->name('index');
    Route::get('/{course}/show', 'CoursesController@show')->name('show');
    Route::get('search', 'CoursesController@search')->name('search');
    Route::post('{course}/request', 'CoursesController@request')
        ->middleware('auth')
        ->name('request');
});

//======================================//
//=========== Books Routes ===========//
//======================================//
Route::prefix('books')->name('books.')->group(function() {
    Route::get('/', 'BooksController@index')->name('index');
    Route::get('{book}/show', 'BooksController@show')->name('show');
    Route::middleware('auth')->group(function() {
        Route::get('{book}/view', 'BooksController@view')->name('view');
        Route::get('{book}/download', 'BooksController@download')->name('download');
        Route::get('{book}/buy', 'BooksController@buy')->name('buy');
        Route::get('paypal/checkout', 'PayPalController@checkout_book')
            ->name('checkout');
        Route::get('paypal/checkout/success', 'PayPalController@checkout_book_success')
            ->name('checkout_success');
    });
});

//======================================//
//=========== Videos Routes ===========//
//======================================//
Route::prefix('videos')->name('videos.')->group(function() {
    Route::get('/', 'VideosController@index')->name('index');
    Route::get('{video}/show', 'VideosController@show')->name('show');
});

resources/views/layouts/app.blade.php
@include('layouts.header')

@yield('content')

@include('layouts.footer')

resources/views/layouts/footer.blade.php
<footer id="footer">
    <div class="footer-top">
        <div class="container">
            <div class="row">
                <div class="col-sm-6 col-md-4">
                    <h5>أقسام الإختبارات</h5>
                    <ul class="footer-link">
                        @foreach($categories as $category)
                            <li><a href="{{ route('categories.show', $category) }}">{{ $category->cat_name }}</a></li>
                        @endforeach
                        {{--<li><a href="terms%20&%20conditions.html">الإختبارات اللغوية</a></li>--}}
                        {{--<li><a href="privacy-policy.html">الإختبارات المهنية</a></li>--}}
                        {{--<li><a href="contact-us.html">الإختبارات الدولية</a></li>--}}
                    </ul>
                </div>
                @php($pages = \App\Page::where('active', 1)->get())
                <div class="col-sm-6 col-md-4">
                    <div class="col-md-offset-1 col-sm-6 col-md-5 col-xs-6">
                        <h5>روابط مهمة</h5>
                        <ul class="footer-link">
                            <li><a href="{{ route('about') }}">عن قياس2030</a></li>
                            <li><a href="{{ route('contact') }}">اتصل بنا</a></li>
                            @foreach($pages as $page)
                                <li><a href="{{ route('pages', $page) }}">{{ $page->title }}</a></li>
                            @endforeach
                            {{--<li><a href="terms%20&%20conditions.html">الشروط والأحكام</a></li>--}}
                            {{--<li><a href="privacy-policy.html">سياسة الخصوصية</a></li>--}}
                        </ul>
                    </div>
                </div>
                <div class="col-sm-6 col-md-4">
                    <h5>مراسلة الإدارة</h5>
                    <div class="contact-view">
                        <div class="contact-slide">
                            <p><i class="fa fa-phone"></i>{{ setting('site.phone') }}</p>
                        </div>
                        <div class="contact-slide">
                            <p><i class="fa fa-envelope"></i><a href="mailTo:{{ setting('site.email') }}">{{ setting('site.email') }}</a></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-sm-8">
                <div class="copy-right">
                    <p>Copyright © <span class="year">2019</span> قياس2030</p>
                </div>
            </div>
            <div class="col-sm-4 ">
                <div class="social-media">
                    <ul>
                        <li><a href="{{ setting('site.facebook', '#') }}"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="{{ setting('site.twitter', '#') }}"><i class="fa fa-twitter"></i></a></li>
                        {{--<li><a href="#"><i class="fa fa-skype"></i></a></li>--}}
                        <li><a href="{{ setting('site.youtube', '#') }}"><i class="fa fa-youtube"></i></a></li>
                        <li><a href="{{ setting('site.instagram', '#') }}"><i class="fa fa-instagram"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</footer>
</div>
<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->

<script type="text/javascript" src="{{ asset('js/jquery-1.12.4.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/bootstrap.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/owl.carousel.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/jquery.form-validator.min.js') }}"></script>
<script type='text/javascript' src='https://maps.google.com/maps/api/js?key=AIzaSyAciPo9R0k3pzmKu6DKhGk6kipPnsTk5NU'></script>
<script type="text/javascript" src="{{ asset('js/map-styleMain.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/placeholder.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/coustem.js') }}"></script>
@yield('scripts')
<script>
    function openForm() {
        document.getElementById("myForm").style.display = "block";
    }

    function closeForm() {
        document.getElementById("myForm").style.display = "none";
    }
</script>
</body>
</html>

resources/views/layouts/header.blade.php
<!DOCTYPE html>
<html lang="en" dir="rtl">
<head>
    <!-- Meta information -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"><!-- Mobile Specific Metas -->

    <!-- Title -->
    <title>{{ config('app.name') . (@$title ? ' | ' . $title : '') }}</title>

    <!-- favicon icon -->
    <link rel="shortcut icon" href="{{ asset('images/Favicon.ico') }}">

    <!-- CSS Stylesheet -->
    <link href="{{ asset('css/bootstrap.css') }}" rel="stylesheet"><!-- bootstrap css -->
    <link href="{{ asset('css/bootstrap-rtl.min.css') }}" rel="stylesheet"><!-- bootstrap rtl css -->
    <link href="{{ asset('css/owl.carousel.css') }}" rel="stylesheet"><!-- carousel Slider -->
    <link href="{{ asset('css/font-awesome.css') }}" rel="stylesheet"><!-- font awesome -->
    <link href="{{ asset('css/loader.css') }}" rel="stylesheet"><!--  loader css -->
    <link href="{{ asset('css/docs.css') }}" rel="stylesheet"><!--  template structure css -->
    <link href="{{ asset('css/jquery.countdown.css') }}" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Arima+Madurai:100,200,300,400,500,700,800,900%7CPT+Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Tajawal:500&display=swap" rel="stylesheet">
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->

</head>

<body>
    <div class="wapper">
        <div id="loader-wrapper">
        <div id="loader"></div>
        <div class="loader-section section-left"></div>
        <div class="loader-section section-right"></div>
        </div>
        <div class="quck-nav">
            <div class="container">
                <div class="contact-no Tajawal-font">
                    @php($now = \Carbon\Carbon::now('Asia/Riyadh'))
                    <i class="fa fa-calendar"></i>
                    {{ $now->day }}
                    {{ $ar_month[$now->shortEnglishMonth] }}
                    {{ $now->year }}
                </div>
                <div class="quck-right">
                    @auth('web')
                        <div class="right-link Tajawal-font">
                            <a href="{{ route('user.notifications') }}">
                                <i class="fa fa-bell" aria-hidden="true"></i>إشعاراتي
                            </a>
                        </div>
                        <div class="right-link Tajawal-font">
                            <a href="{{ route('user.profile') }}">
                                <i class="fa fa-bell" aria-hidden="true"></i>حسابي
                            </a>
                        </div>
                        <div class="right-link Tajawal-font">
                            <form action="{{ route('logout') }}" method="post" class="form-inline">
                                {{ csrf_field() }}
                                <button type="submit" class="btn-sm btn-link" style="color: white;">
                                    <i class="fa fa-sign-out" aria-hidden="true"></i>
                                    خروج
                                </button>
                            </form>
                        </div>
                    @else
                        <div class="right-link Tajawal-font"><a href="{{ route('login') }}"><i class="fa  fa-user"></i>دخول / إنشاء حساب</a></div>
                    @endauth
                </div>
            </div>
        </div>
        <header id="header">
            <div class="container">
                <nav id="nav-main">
                    <div class="navbar navbar-inverse">
                        <div class="navbar-header">
                            <a href="{{ route('home') }}" class="navbar-brand">
                                <img src="{{ asset('images/logo.png') }}" alt="">
                            </a>
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                        </div>
                        <div class="navbar-collapse collapse">
                            <ul class="nav navbar-nav">
                                <li class="sub-menu">
                                    <a class="Tajawal-font" href="{{ route('home') }}">الرئيسية</a>
                                </li>
                                <li class="sub-menu mega-menu">
                                    <a class="Tajawal-font" href="{{ route('about') }}">عن قياس2030</a>
                                </li>
                                <li class="mega-menu sub-menu">
                                    <a class="Tajawal-font" href="{{ route('categories.index') }}">إختبارات قياس</a>
                                    <div class="menu-view">
                                        <div class="row">
                                            @foreach($categories as $category)
                                                @if($category->exam_count() == 0)
                                                    @continue
                                                @endif
                                                <div class="col-sm-3">
                                                    <div class="menu-title">
                                                        <a href="{{ route('categories.show', $category) }}">{{ $category->cat_name }}</a>
                                                    </div>
                                                    @if($category->sub_categories->count())
                                                        <ul>
                                                            @foreach($category->sub_categories->take(4) as $sub_category)
                                                                @if($sub_category->exam_count() == 0)
                                                                    @continue
                                                                @endif
                                                                <li>
                                                                    <a class="Tajawal-font" href="{{ route('categories.show', $sub_category) }}">
                                                                        {{ $sub_category->cat_name }}
                                                                        <span class="muted-text" style="display: inline-block">
                                                                            ({{ $sub_category->exam_count() }} إختبار)
                                                                        </span>
                                                                    </a>
                                                                </li>
                                                            @endforeach
                                                        </ul>
                                                    @endif
                                                </div>
                                            @endforeach
                                        </div>
                                    </div>
                                </li>
                                <li><a class="Tajawal-font" href="{{ route('courses.index') }}">الدورات التدريبية</a></li>
                                <li class="sub-menu mega-menu">
                                    <a class="Tajawal-font" href="{{ route('books.index') }}">الكتب الإلكترونية</a>
                                </li>
                                <li class="sub-menu mega-menu">
                                    <a class="Tajawal-font" href="{{ route('news.index') }}">أخبارنا</a>
                                </li>
                                <li class="sub-menu">
                                    <a class="Tajawal-font" href="{{ route('videos.index') }}">مكتبة الفيديو</a>
                                </li>
                                <li class="sub-menu">
                                    <a class="Tajawal-font" href="{{ route('contact') }}">تواصل معنا</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </nav>
            </div>
        </header>